### ISSUE TITLE
Workflow restart in UI

### ISSUE THREAD

**Issue by MrMcX** [ubilab-escape/operator#15]
Kannst du nach Abschluss des Workflows ein "stop" retained im Topic gameControl schicken? Sonst denkt die UI, dass die Logik noch läuft

**Comment by jrebmann** [comment]
Ich würde die control Queue nicht für Status verwenden

1. Führt das zu Problemen, da Status und Command im Programm unterschieden werden müssen
1. Die Queue muss bei Start aufgeräumt werden.

Wie wäre vielleicht die Idee, wenn wir einfach als letzten Schritt die retained Nachricht in der Status-Queue einfach löschen? => Status == null => Spiel läuft nicht

**Comment by MrMcX** [comment]
Wie du schon privat geschrieben hast, können die Befehle retained Probleme verursachen. Wie wäre es mit einem zweiten Topic (z.B. 1/gameControl/status), wo du immer den aktuellen Befehl retained reinschreibst und den dann nach dem Abschluss löschst?

**Comment by jrebmann** [comment]
Bessere Idee: Ich mache einfach folgendes: 1/gameControl == null => Kein aktives Spiel!
Dann leere ich einfach am Ende die gameControl retained Einträge

**Comment by MrMcX** [comment]
Das Problem ist, dass die UI nicht merkt, wenn etwas auf null gesetzt wird, da das keine wirkliche Nachricht ist - und regelmäßig checken halte ich nicht für sinnvoll

**Comment by jrebmann** [comment]
also bei mir wird die nachricht "null" gesendet wenn ich subscriped bin
