### ISSUE TITLE
Display time on in-room timer

### ISSUE THREAD

**Issue by MrMcX** [ubilab-escape/operator#18]
```
{ "METHOD" : "TRIGGER", "STATE" :   "setTimer", "DATA" : "5400"} #Unity is second
{ "METHOD" : "TRIGGER", "STATE" : "resetTimer" }
{ "METHOD" : "TRIGGER", "STATE" : "startTimer" }
{ "METHOD" : "TRIGGER", "STATE" :  "stopTimer" }
```

Könnte man das in die Logik einbauen?

**Comment by jrebmann** [comment]
Für was brauchen wir das? Die Spielzeit ist doch direkt an die Grundbefehle START, STOP und PAUSE geknüpft. Was genau ist der use case dafür?

**Comment by MrMcX** [comment]
Das ist die Anzeige auf dem Display im Raum...

**Comment by jrebmann** [comment]
Entscheidung: Spielzeit wird sekündlich gepushed und Clients können sich an der Zeit bedienen.
