### ISSUE TITLE
Set initial state

### ISSUE THREAD

**Issue by MrMcX** [ubilab-escape/operator#24]
Initial state should be set after start is selected in UI:

- Close both doors
- reset other puzzles?

`method: message, state: restart` (doors)

**Comment by jrebmann** [comment]
Zu: "Close both doors"
Sollen wir das nicht in den Workflow mit aufnehmen? Dann sind wir flexibler.

Zu: "Reset other puzzles"
Nachdem wir ein trigger:off an das Rätsel geschickt haben, sollte der Reset ja schon passiert sein oder?

**Comment by MrMcX** [comment]
>  Sollen wir das nicht in den Workflow mit aufnehmen? Dann sind wir flexibler.

Du musst sagen, was da für dich am einfachsten ist...

>  Nachdem wir ein trigger:off an das Rätsel geschickt haben, sollte der Reset ja schon passiert sein oder?

Ich wollte das da vor allem stehen haben, damit wir alle Gruppen mal fragen, ob das mit dem resetten bei denen klappt oder ob die was besonderes brauchen

**Comment by MrMcX** [comment]
- doors (#40)
- group 2 - environment
- group 4 - doors and anteroom riddle
- group 5 - safe
- group 6 - prototype
- group 7 - server room door riddle
- group 8 - server room terminal
