### ISSUE TITLE
Trigger:on should be sendable repeatly

### ISSUE THREAD

**Issue by jrebmann** [ubilab-escape/operator#49]

**Comment by MrMcX** [comment]
Was ist hier das Problem?

**Comment by jrebmann** [comment]
Hier geht es einfach darum, dass zur Action "Skip" eine neue Action "On" in der UI eingeführt wird, um einen trigger:on an das Gerät sendet. Ich denke in dem Zuge macht es auch Sinn, gleich ein "Off" als Action anzubieten.

Vorschlag:
1/gameControl | ON \<name\>
1/gameControl | OFF \<name\>

**Comment by MrMcX** [comment]
Muss das on/off überhaupt über die Logik laufen? Ich könnte doch in der UI direkt einen Trigger schicken - andererseits bräuchte ich dann den entsprechenden Topic Namen und gerade bei Blöcken wird das eventuell kompliziert
