### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by jrebmann** [ubilab-escape/operator#55]
Following checklist created from the grading requirements of phil:

- [x] think about how to present your project/puzzle when the room is not running
- [x] be prepared to illustrate your personal contribution
- [x] how to control the system via MQTT.
- [x] code is commented sufficiently
- [X] make sure your README file on github contains a motivation for your puzzle
- [X] make sure your README file on github contains an instruction
- [X] how to get the code to work if somebody likes to rebuild your system
- [X] make sure all code and files for your puzzles are on github

**Comment by jrebmann** [comment]
Gibt es zu den beiden offenen Punkten irgendwelche Neuigkeiten.
Wurde dazu am Freitag noch etwas gesagt?

**Comment by MrMcX** [comment]
Leider nein, ich wollte/werde nochmal nachfragen
