### ISSUE TITLE
Send hint when lab room doors opened

### ISSUE THREAD

**Issue by MrMcX** [ubilab-escape/operator#69]
"Please close the door"
Maybe repeat after some time?

**Comment by MrMcX** [comment]
Das kann ich dann auch gerne übernehmen, da kann ich ja den Code aus #63 wiederverwenden

**Comment by jrebmann** [comment]
Das wäre glaube ich am sinnvollsten. Bekommst du das noch unter? Oder brauchst du hier Unterstützung?
