### ISSUE TITLE
Skipping lab room goes directly to Simon says

### ISSUE THREAD

**Issue by MrMcX** [ubilab-escape/operator#74]

**Comment by MrMcX** [comment]
Not always

**Comment by jrebmann** [comment]
ich verstehe diesen Bug-Report leider nicht :(

**Comment by MrMcX** [comment]
Am Freitag hatten wir beim Testen mehrfach (aber nicht immer) den Fall, dass das Skippen des Blocks "Lab room" der Block "Server room" ignoriert wurde (war im Graph noch grau) und die Logik direkt zum "Simon riddle" weiter gegangen ist. Allerdings haben die Rätsel im Block "Server room" trotzdem ein trigger on bekommen

**Comment by jrebmann** [comment]
Dieses Phänomen kann ich bei mir nicht nachstellen.
Ich habe aber die Befürchtung, dass es etwas mit ungüstigem Timing zu tun hat.
Hast du bei den Tests vielleicht zufällig einen reproduzierbaren Ablauf gefunden?

**Comment by jrebmann** [comment]
Okey ich habe eine reproduzierbare Abfolge gefunden:
SKIP Entrance room
SKIP Solve safe
SKIP Solve door riddle
