### ISSUE TITLE
Clean up MQTT queue if the riddle is started

### ISSUE THREAD

**Issue by jrebmann** [ubilab-escape/operator#8]

**Comment by MrMcX** [comment]
Der folgende Befehl in der Kommandozeile sollte das erreichen, vielleicht kannst du, @CuddlySheep das direkt aus Python ausführen, wenn du den "start" Befehl bekommst:
`mosquitto_sub -h 10.0.0.2 -t "#" --retained-only -v | while read line; do mosquitto_pub -h 10.0.0.2 -t "${line% *}" -r -n; done`

**Comment by MrMcX** [comment]
Für die UI wäre es eventuell schön, wenn man das sowohl nach dem Ende als auch nach dem Starten macht, da sonst nach dem Ende ganz viele Rätsel angezeigt werden

**Comment by jrebmann** [comment]
Pro topic kann es ja nur eine retained Nachricht geben ... aus diesem Grund würde ich einfach die retained Nachrichten des aktuellen Channels löschen:
self.client.publish(self.game_state_topic, None, 2, True)

**Comment by MrMcX** [comment]
Genau, nur müssen wir das ja für alle Topics machen
Und der Befehl oben macht das sogar für Topics, die wir nicht definiert haben

**Comment by MrMcX** [comment]
`--retained-only` gibt es nicht auf Ubuntu 18.04

Wir könnten über den PPA `sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa` auf die aktuellste *dev* Version aktualisieren oder Ubuntu auf 19.10 aktualisieren, beides bringt aber potentielle Inkompatibilitäten mit. Danach ist der Befehl auch etwas kürzer:

`mosquitto_sub -t '#' --remove-retained --retained-only`

Alternativ könnten wir schauen, wie aktuell die *snap* Version ist

**Comment by MrMcX** [comment]
`/snap/bin/mosquitto_sub -t '#' --remove-retained --retained-only` sollte gehen

**Comment by CuddlySheep** [comment]
Warum sollte der gehen, hast du da etwas spezielles gemacht?

**Comment by jrebmann** [comment]
Kann ich diesen Befehl genau so einbauen?

**Comment by MrMcX** [comment]
Jep, der ist getestet
